describe('Shed app ', function() {
  beforeEach(function() {
    cy.visit('http://localhost:3000')
    cy.deleteTestSubject()
    cy.deleteTestSession()
    cy.deleteTestUser()
  })
  it('front page can be opened', function() {
    cy.contains('Pick a subject to practice:')
    cy.contains('Practice clock')
    cy.contains('Start').click()
  })
  it('Login page can be accessed', function() {
    cy.contains('Signup/Login').click()
  })
  it('Logging in and out works', function() {
    cy.contains('Signup/Login').click()
    cy.get('#username').type('testUser')
    cy.get('#password').type('testPassword')
    cy.get('#login-button').click()
    cy.contains('Welcome back testUser!')
    cy.contains('Log out').click()
    cy.contains('Signup/Login')
    cy.contains('Log in to save sessions')
  })
  it('Creating new account works', function() {
    cy.contains('Signup/Login').click()
    cy.contains('Create account').click()
    cy.get('#username').type('cypressUser')
    cy.get('#password').type('cypressPassword')
    cy.get('#signup-button').click()
    cy.contains('New user cypressUser added!')
    cy.contains('Back').click()
  })
  describe('When logged in', function() {
    beforeEach(function() {
      cy.contains('Signup/Login').click()
      cy.get('#username').type('testUser')
      cy.get('#password').type('testPassword')
      cy.get('#login-button').click()
    })
    it('Subjects can be added', function() {
      cy.contains('Add subject').click()
      cy.get('#subject').type('testSubject')
      cy.get('#description').type('Subject for cypress')
      cy.get('#submit-button').click()
      cy.contains('testSubject added as subject!')
      cy.contains('Back').click()
      cy.get('#subjectMenu').click()
      cy.contains('testSubject')
    })
    it('Sessions can be saved', function() {
      cy.contains('Add subject').click()
      cy.get('#subject').type('testSubject')
      cy.get('#description').type('Subject for cypress')
      cy.get('#submit-button').click()
      cy.contains('testSubject added as subject!')
      cy.contains('Back').click()
      cy.get('#subjectMenu').click()
      cy.contains('testSubject').click()
      cy.contains('Start').click()
      cy.contains('Now practicing testSubject')
      cy.contains('Stop').click()
      cy.get('#notes').type('cypressSession')
      cy.contains('Finish session').click()
      cy.contains('Yes').click()
      cy.contains('History').click()
      cy.contains('testSubject')
      cy.contains('Notes: cypressSession')
    })
  })
})