name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run lint
      - name: unit tests
        run: npm test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          command: npm run test:e2e
          start: npm run start
          wait-on: http://localhost:3000
          wait-on-timeout: 1000